app/models.py
from mongoengine import StringField, IntField, BooleanField, ReferenceField, DateTimeField, ListField
from flask_login import UserMixin
from . import db
from . import login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from datetime import datetime


class Role(db.Document):
    meta = {
        'collection': 'roles'
    }
    name = StringField(max_length=64, unique=True)
    default = BooleanField(default=False)
    permissions = IntField()


class User(UserMixin, db.Document):
    meta = {
        'collection': 'users',
        'ordering': ['-create_at'],
        'strict': False,
    }

    # def __init__(self, **kwargs):
    #     super(User, self).__init__(**kwargs)
    #     self.role_id = Permission.FOLLOW | Permission.COMMENT | Permission.WRITE_ARTICLES

    email = StringField()
    username = StringField()
    password_hash = StringField(max_length=128)
    role_id = IntField()
    confirmed = BooleanField(default=False)
    about_me = StringField()
    member_since = DateTimeField(default=datetime.utcnow)
    last_seen = DateTimeField(default=datetime.utcnow)
    role = ReferenceField(Role)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': str(self.id)})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != str(self.id):
            return False
        self.confirmed = True
        self.save()
        return True

    def is_admin(self):
        return self.role is not None and (self.role.permissions & Permission.ADMINISTER) == Permission.ADMINISTER


@login_manager.user_loader
def load_user(user_id):
    return User.objects(id=user_id).first()


class Permission:
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, Email
from ..models import Permission


class EditProfileForm(FlaskForm):
    about_me = StringField('about me')
    submit = SubmitField('submit')


class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField('Username')
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', choices=[(Permission.FOLLOW | Permission.COMMENT | Permission.WRITE_ARTICLES, 'User'),
                                        (Permission.FOLLOW | Permission.COMMENT | Permission.WRITE_ARTICLES |
                                         Permission.MODERATE_COMMENTS, 'Moderator'),
                                        (Permission.ADMINISTER, 'Administrator')], coerce=int)
    about_me = TextAreaField('About me')
    submit = SubmitField()

app/__init__.py
from flask import Flask
from flask_mongoengine import MongoEngine
from flask_login import LoginManager
from config import config  # 绝对引用
# from ..config import config  # 相对引用
from flask_bootstrap import Bootstrap
from flask_mail import Mail


db = MongoEngine()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()

mail = Mail()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from flask import render_template, abort, flash, redirect, url_for
from ..models import User
from flask_login import login_required, current_user
from .forms import EditProfileForm, EditProfileAdminForm


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/user/<username>')
def user(username):
    user = User.objects(username=username).first()
    if user is None:
        abort(404)
    # user = User.objects.first_or_404(username=username)
    return render_template('user.html', user=user)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.about_me = form.about_me.data
        current_user.save()
        flash('档案更新成功')
        return redirect(url_for('main.user', username=current_user.username))
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@main.route('/edit-profile/<id>', methods=['GET', 'POST'])
@login_required
def edit_profile_admin(id):
    # user = User.objects.first_or_404(id=id)
    user = User.objects(id=id).first()
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role_id = form.role.data
        user.about_me = form.about_me.data

        user.save()
        flash('档案更新成功')
        return redirect(url_for('main.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}



{% block head %}

{{ super() }}

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

{% endblock %}

{#{% block navbar %}#}
{#<ul class="nav navbar-nav navbar-right">#}
{#    {% if current_user.is_authenticated %}#}
{#    <li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>#}
{#    {% else %}#}
{#    <li><a href="{{ url_for('auth.login') }}">Sign In</a></li>#}
{#    {% endif %}#}
{#</ul>#}
{#{% endblock %}#}
{% block navbar %}

<div class="navbar navbar-inverse" role="navigation">

    <div class="container">

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>

        </div>

        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav">

                <li><a href="{{ url_for('main.index') }}">Home</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">

                {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
                    </li>

                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>

                {% else %}

                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>

                {% endif %}

            </ul>

        </div>

    </div>

</div>

{% endblock %}
{% block content %}

<div class="container">

    {% for message in get_flashed_messages() %}

    <div class="alert alert-warning">

        <button type="button" class="close" data-dismiss="alert">&times;</button>

        {{ message }}

    </div>

    {% endfor %}



    {% block page_content %}{% endblock %}
</div>

{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - edit{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>edit</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
Hello,
{% if current_user.is_authenticated %}
    {{ current_user.username }}
{% else %}
    Stranger
{% endif %}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
<h1>{{ user.username }}</h1>
{#member since {{ moment(user.member_since).format('L') }}#}
{#last seen {{ moment(user.last_seen).fromNow() }}#}
last seen {{ user.last_seen }}
</div>
    {% if user == current_user %}
        <a href="{{ url_for('main.edit_profile') }}" class="btn btn-default">Edit Profile</a>
    {% endif %}
    {% if current_user.is_admin() %}
        <a href="{{ url_for('main.edit_profile_admin', id=user.id) }}" class="btn btn-danger">Edit Profile [Admin]</a>
    {% endif %}
{% endblock %}